module.exports = {
  getPdfById: require("./getPdfById.controller"),
  allPdfs: require("./getAllPdf.controller"),
  deletePdf: require("./deletePdfById.controller"),
  createSites: require("./createSite.controller"),
  allSites: require("./getAllSites.controller"),
  userLogin: require("./userLogin.controller"),
  userRegister: require("./userRegister.controller"),
  deleteSite: require("./deleteSite.controller"),
  updateSite: require("./updateSite.controller"),
  verifyViewCode: require("./verifyCode.controller"),
  createPdfRaport: require("./createRaport.controller"),
  getRaports: require("./getPdfRaportsById.controller"),
  getUserDataById: require("./fetchUserData.controller"),
  formData: require("./formDataUpload.controller"),
  forgotUserPassword: require("./resetPassword.controller"),
  public: require("./publicetPdfData.controller"),
  updateUserData: require("./updateUserDate.controller"),
  verification: require("./accountVerification.controller"),
  Notification: require("./fetchNotifications.controller"),
  contactUs: require("./contactUs.controller"),
};
